# Generated by Django 4.1.4 on 2022-12-31 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_bookinstance_borrower_alter_bookinstance_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("can_mark_returned", "Set book as returned"),),
            },
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f2c9bb91-2171-4f4e-98ba-65a777337665"),
                help_text="Unique ID for this particular book across whole librar",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
